print("\"C:\\Download\\'hello\tworld'.py\"")
print("\nPython Escape Characters")
print("Single Quote : \\'")
print('Quote : \\"')
print("Backslash : \\\\")
print("New LIne : \\n")
print("Backspace : \\b")
